#!/bin/bash

echo -e "Post-merge healthcheck\n"
echo "Current time: $(date)"
echo -e "\n"
echo -e "Disk space usage:\n"
df -h

echo -e "Memory use:\n"
free -h

echo -e "Running tasks:\n"
ps -aux
echo "-----------------------"
echo "Healthcheck complete"
