#!/bin/bash

echo -e "Post-merge healthcheck\n"
echo "Current time: $(date)"
echo -e "\n\n"
echo "Disk space usage:\n"
df -h

echo "Memory use:\n"
free -h

echo "Running tasks:\n"
ps -aux

echo "Healthcheck complete"
